version: '3.1'

services:
  db:
    container_name: okta-restaurants
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: okta-feed-me-well-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
